# Pandas Analysis 

Load in the data.

In [2]:
# Install datasets Library (if not already installed)
# !pip install -U datasets

# Importing Libraries
import pandas as pd
from datasets import load_dataset

# Loading Data
dataset = load_dataset('lukebarousse/data_jobs')
df = dataset['train'].to_pandas()

# Data Cleanup
df['job_posted_date'] = pd.to_datetime(df['job_posted_date'])

## Descriptive Statistics

### Describe()

#### Notes

For a basic overview we'll be using `describe()`.
* It gets the following (for columns with numeric data):
  * count
  * mean
  * std
  * min
  * max
* Great for getting a quick overview of the basic stats for the table.
* It automatically skips NaN values. 

#### Example

Use `describe()` on our DataFrame.

In [4]:
df.describe()

                     job_posted_date  salary_year_avg  salary_hour_avg
count                         785741     22003.000000     10662.000000
mean   2023-06-25 16:02:11.860248576    123286.274072        47.016598
min              2023-01-01 00:00:04     15000.000000         8.000000
25%              2023-03-20 10:05:48     90000.000000        27.500000
50%              2023-06-29 06:11:38    115000.000000        45.980000
75%              2023-09-27 01:01:16    150000.000000        61.159996
max              2023-12-31 23:59:58    960000.000000       391.000000
std                              NaN     48312.449482        21.890738

You can also use it on individual columns. If we just wanted to look at `salary_year_avg` then we'd do:

In [5]:
df['job_posted_date'].describe()

count                           785741
mean     2023-06-25 16:02:11.860248576
min                2023-01-01 00:00:04
25%                2023-03-20 10:05:48
50%                2023-06-29 06:11:38
75%                2023-09-27 01:01:16
max                2023-12-31 23:59:58
Name: job_posted_date, dtype: object

### Common Data Analysis Methods

#### Notes 

But there are other methods like:
* `df.sum()` - Sum of values
* `df.cumsum()` - Cummulative sum of values
* `df.min()`/`df.max()` - Minimum/maximum values
* `df.idxmin()`/`df.idxmax()` - Indexes of minimum/Maximum value
* `df.mean()` - Mean of values
* `df.median()` - Median of values
* `df.mode()` - Mode of the values 
* `series.value_counts()` - Counts of unique values for a Series (aka a column)
    * Typically used for counting *unique occurrences* within a single column. 
    * It's not applicable to an entire DataFrame without specifying a column.
* Depending on the method, you can apply it directly to a DataFrame or a Series.

#### Examples

Let's get the count of the values in each column within the entire DataFrame.

In [6]:
df.count()

job_title_short          785741
job_title                785740
job_location             784696
job_via                  785733
job_schedule_type        773074
job_work_from_home       785741
search_location          785741
job_posted_date          785741
job_no_degree_mention    785741
job_health_insurance     785741
job_country              785692
salary_rate               33067
salary_year_avg           22003
salary_hour_avg           10662
company_name             785723
job_skills               668704
job_type_skills          668704
dtype: int64

This is good to get a general overview of the DataFrame but it isn't that useful to us right now. Let's do some counts on specific columns:

Get the mode of the `'salary_year_avg'` column. - gives the frequent value of the specific column

In [7]:
df['salary_year_avg'].mode()

0    90000.0
Name: salary_year_avg, dtype: float64

Now we are going to get the index value of the max value of `salary_year_avg`.

In [9]:
df['salary_year_avg'].idxmax()

554784

It gave us the index (row) = 357614. Remember how to get a row by the index number? We'll use `iloc` and inspect this. 

It looks correct based on the maximum value we saw when using `describe()`.

In [11]:
df.iloc[554784]

job_title_short                                           Data Scientist
job_title                                                 Data Scientist
job_location                                                 Madison, SD
job_via                                    via Cooperative Career Center
job_schedule_type                                              Full-time
job_work_from_home                                                 False
search_location                                  Illinois, United States
job_posted_date                                      2023-05-04 19:06:06
job_no_degree_mention                                              False
job_health_insurance                                                True
job_country                                                United States
salary_rate                                                         year
salary_year_avg                                                 960000.0
salary_hour_avg                                                      NaN
company_name                 East River Electric Power Cooperative, Inc.
job_skills                                ['java', 'c++', 'python', 'r']
job_type_skills          {'programming': ['java', 'c++', 'python', 'r']}
Name: 554784, dtype: object

How about the *unique* count of job titles? - unique gives the unique value , value counts gives the total count of unique value in columns

In [13]:
df.job_title_short.value_counts()

job_title_short
Data Analyst                 196075
Data Engineer                186241
Data Scientist               172286
Business Analyst              49063
Software Engineer             44929
Senior Data Engineer          44563
Senior Data Scientist         36957
Senior Data Analyst           29216
Machine Learning Engineer     14080
Cloud Engineer                12331
Name: count, dtype: int64

## Aggregation



### Groupby()

#### Notes

* Use `groupby` to group your DataFrame by the unique values in a specific column.
* Lets you perform aggregation (e.g. mean, sum) on the grouped data.
* Aggregations you can perform:
  * `mean()`: Computes the mean of the groups
  * `sum()`: Calculates the sum of the group values
  * `median()`: Finds the median of each group
  * `min()` and `max()`: Determine the minimum and maximum values within each group
  * Counts:
    * `count()`: Counts the number of non-NA/null entries in each group
    * `size()`: Returns the size of each group (including NA/null values)
  * `std()` and `var()`: Calculate the standard deviation and variance of groups
  * `first()` and `last()`: Get the first and last row of each group
  * `unique()`: Counts the number of unique non-NA/null values in each group

#### Examples

If we want to find the average yearly salary by `job_title_short`.

In [17]:
df.groupby('job_title_short')['salary_year_avg'].mean()

job_title_short
Business Analyst              91082.612833
Cloud Engineer               111268.453846
Data Analyst                  93841.907854
Data Engineer                130125.604250
Data Scientist               135988.837171
Machine Learning Engineer    126774.315972
Senior Data Analyst          113911.363665
Senior Data Engineer         145840.611624
Senior Data Scientist        154206.292996
Software Engineer            113393.760054
Name: salary_year_avg, dtype: float64

What about the median of the salary by job title short?

In [18]:
df.groupby('job_title_short')['salary_year_avg'].median()

job_title_short
Business Analyst              85000.0
Cloud Engineer                90000.0
Data Analyst                  90000.0
Data Engineer                125000.0
Data Scientist               127500.0
Machine Learning Engineer    106415.0
Senior Data Analyst          111175.0
Senior Data Engineer         147500.0
Senior Data Scientist        155500.0
Software Engineer             99150.0
Name: salary_year_avg, dtype: float64

### Agg()

#### Notes

* `agg()` lets you apply multiple functions at once.
* You can pass a list of functions to `agg()` to apply them all to the grouped data, or a dictionary to apply specific functions to specific columns. 


#### Example 

For each job title (`job_title_short`) let's get the minimum and maximum values for the salary.

In [23]:
df.groupby('job_title_short')['salary_year_avg'].agg(['min','max'])

                               min       max
job_title_short
Business Analyst           16500.0  387460.0
Cloud Engineer             42000.0  280000.0
Data Analyst               25000.0  650000.0
Data Engineer              15000.0  525000.0
Data Scientist             27000.0  960000.0
Machine Learning Engineer  30000.0  325000.0
Senior Data Analyst        30000.0  425000.0
Senior Data Engineer       35000.0  425000.0
Senior Data Scientist      45000.0  890000.0
Software Engineer          28000.0  375000.0